apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    name.os.template.kubevirt.io/centos8.0: CentOS 8.0
    validations: |
      [
        {
          "name": "minimal-required-memory",
          "path": "jsonpath::.spec.domain.resources.requests.memory",
          "rule": "integer",
          "message": "This VM requires more memory.",
          "min": 1073741824
        }
      ]
  labels:
    flavor.template.kubevirt.io/medium: "true"
    os.template.kubevirt.io/centos8.0: "true"
    template.kubevirt.io/type: vm
    vm.kubevirt.io/template: centos8-server-medium-v0.7.0
    vm.kubevirt.io/template.namespace: openshift
    workload.template.kubevirt.io/server: "true"
  name: centos-8-template
  namespace: default
objects:
- apiVersion: kubevirt.io/v1alpha3
  kind: VirtualMachine
  metadata:
    name: ${NAME}
  spec:
    dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1alpha1
      kind: DataVolume
      metadata:
        name: ${NAME}-disk0
      spec:
        pvc:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: hostpath-provisioner
          volumeMode: Filesystem
        source:
          http:
            url: http://172.30.109.145:9000/images/centos-8-x86_64
    running: false
    template:
      metadata:
        labels:
          kubevirt.io/domain: ${NAME}
          kubevirt.io/size: medium
      spec:
        domain:
          cpu:
            cores: 1
            sockets: 1
            threads: 1
          devices:
            disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: disk0
            - disk:
                bus: virtio
              name: cloudinitdisk
            interfaces:
            - masquerade: {}
              model: virtio
              name: nic-0
            networkInterfaceMultiqueue: true
            rng: {}
          machine:
            type: pc-q35-rhel8.1.0
          resources:
            requests:
              memory: 4Gi
        evictionStrategy: LiveMigrate
        hostname: ${NAME}
        networks:
        - name: nic-0
          pod: {}
        terminationGracePeriodSeconds: 0
        volumes:
        - dataVolume:
            name: ${NAME}-disk0
          name: disk0
        - cloudInitNoCloud:
            userData: |
              name: default
              ssh_authorized_keys:
              - |
                ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDGUdoILxHMIW5AKQf5qm6hwJ0dJXDJVK+Fgs9D6mA0j/Brp1dVi9tqpyuIrQA14q3BTq4QwDFTjqC5LEe72Beam9/oJkgHfzTmUUr39eswd07+qaNOMCxM0A5AoMlj+plTgaSbzUSqTupxDQAXGKfnAiJiNdLVOobCpHMI1ZM3Odvb+Ng+vFlORvX29aLWz1jntCL9Ec9SMNNnlUFpiREVMk70CG7YSZqHEq323xCP10Uc9exM+OBRCY0lIeRa6bfWPQdb6s2Bcj7RajnvqIh2wrg2XMKDuQlgPkkQIYhVY52UDfBJg/YW3uwylxEJmpIqyNCXgfeOvwD9/F/6BeQ0k5iIC3yrjZ7AwSFATio8vAf6LrgkPl4HsFQRR54L943vVVgglYFDr2z5iP/6qoIiFef+C+chZYe+NfgB1AU3+NDwj4GwcKFGEFnyKnzdEKkOMh/yGUA1dBkjbewL1QyolbqnLaSfmC7aveX5RmqexuWh27cBkoUBCPSRQ6XFzBx8Qtng78mS+PMj2m+Q1FymKUIuMk7fiMLr+4UbWIfSfbzyBt/072GOIETIGVEjHvjG6igV2z0OA1QYeRnben4KLz0y+33ns19Vj3Z57d1OVXG+bI3CX5a6E8V3ULDhf9eSkgd19eKSquJN99Pe/lz0TmnVoKIm4sx6kEmo4gY5Ww== lars@madhatter
          name: cloudinitdisk
parameters:
- description: Name for the new VM
  name: NAME
  required: true
